name: CI
on:
  pull_request:
  push:
    branches:
      - 'main'
defaults:
  run:
    working-directory: v2
env:
  go-version: 1.18
jobs:
  test:
    name: Small test
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ env.go-version }}
      - run: make setup
      - run: make test-tools
      - run: make check-generate
      - run: make code-check
      - run: make test
        timeout-minutes: 20
      - run: make test-dcnet
        timeout-minutes: 20
      - run: make test-vm
        timeout-minutes: 20
  e2e:
    name: End-to-end Test
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - id: auth
        uses: google-github-actions/auth@v0.8.1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
      - uses: google-github-actions/setup-gcloud@v0.6.0
      - name: Run e2e test on GCP instance
        run: ../bin/run-mtest.sh
      - name: Set the instance lifetime
        run: |
          . ../bin/env
          $GCLOUD compute instances add-metadata ${INSTANCE_NAME} --zone ${ZONE} \
            --metadata shutdown-at=$(date -Iseconds -d+30minutes)
        if: failure()
